apiVersion: batch/v1
kind: Job
metadata:
  name: cpu-8gb-prefect
spec:
  parallelism: 2
  activeDeadlineSeconds: 7200 # 2 hours in seconds
  template:
    metadata:
      name: cpu-8GB-pod-prefect
    spec:
      restartPolicy: Never # Ensure the pods do not restart
      volumes:
        - name: home-volume
          persistentVolumeClaim:
            claimName: dsmillerrunfol-rwm
      containers:
        - name: conda-container
          image: "prefecthq/prefect:2-python3.10"
          volumeMounts:
            - name: home-volume
              mountPath: /kube/home/
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo "Initializing prefect worker."
              prefect config set PREFECT_API_URL="http://128.239.58.222:4200/api"
              prefect worker start --pool "generic-cpu-8GB"
              echo "Prefect initialized, pod will terminate at active duration walltime."
              sleep infinity 
          resources:
            requests:
              memory: "8Gi"
              cpu: "1"